// Generated security tests from static findings (checklist Block 13).

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Finding } from "../types.js";

function header(f: Finding): string {
  const cwe = f.cwe != null ? ` · CWE-${f.cwe}` : "";
  const ow = f.owasp ? ` · OWASP ${f.owasp}` : "";
  return `// Generated by VibeScan — commit this file and run in CI
// Rule: ${f.ruleId}${cwe}${ow}
`;
}

function safeName(s: string): string {
  return s.replace(/[^a-zA-Z0-9_-]+/g, "_").slice(0, 80);
}

export function generateTests(findings: Finding[], outputDir: string): string[] {
  mkdirSync(outputDir, { recursive: true });
  const written: string[] = [];

  findings.forEach((f, i) => {
    const base = `${safeName(f.ruleId)}_${i}`;
    let body = "";

    if (f.ruleId === "injection.prototype-pollution.tainted-flow" || f.findingKind === "PROTOTYPE_POLLUTION") {
      body = `${header(f)}
import { test } from 'node:test';
import assert from 'node:assert';

test('prototype pollution oracle for ${f.ruleId}', async () => {
  const before = Object.getOwnPropertyNames(Object.prototype);
  // TODO: import app and POST payload — wire to your server entry
  // await request(app).post('/endpoint').send({"__proto__": {"x": 1}});
  assert.deepStrictEqual(Object.getOwnPropertyNames(Object.prototype), before);
  assert.strictEqual(({} as { x?: unknown }).x, undefined);
});
`;
    } else if (f.ruleId === "crypto.jwt.weak-secret-literal" || f.ruleId.includes("JWT")) {
      body = `${header(f)}
import { test } from 'node:test';
// TODO: decode token, re-sign with weak secret from tier list, expect 401
test('JWT weak secret forgery for ${f.ruleId}', async () => {
  // const forged = jwt.sign({ role: 'admin' }, 'secret');
  // const res = await request(app).get('/api/me').set('Authorization', 'Bearer ' + forged);
  // assert.strictEqual(res.status, 401);
});
`;
    } else if (f.ruleId === "AUTH-001" || f.message.toLowerCase().includes("bola")) {
      body = `${header(f)}
import { test } from 'node:test';
// TODO: create resource as userA, access as userB, expect 403
test('BOLA two-user access for ${f.ruleId}', async () => {
});
`;
    } else {
      body = `${header(f)}
import { test } from 'node:test';
test('generated check for ${f.ruleId}', async () => {
  // TODO: HTTP oracle — status/body assertions for ${f.message}
});
`;
    }

    const filePath = join(outputDir, `${base}.test.mjs`);
    writeFileSync(filePath, body, "utf-8");
    written.push(filePath);
    f.generatedTest = filePath;
  });

  return written;
}
