// Generated security tests from static findings (checklist Block 13).

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { JWT_WEAK_SECRET_TEST } from "../../attacks/crypto/jwt-weak-test.js";
import type { Finding } from "../types.js";

function header(f: Finding): string {
  const cwe = f.cwe != null ? ` · CWE-${f.cwe}` : "";
  const ow = f.owasp ? ` · OWASP ${f.owasp}` : "";
  const loc =
    f.filePath != null
      ? `\n// Source: ${escapeBlockComment(f.filePath)}:${f.line}`
      : `\n// Source line: ${f.line}`;
  return `// Generated by VibeScan — commit this file and run in CI
// Rule: ${escapeBlockComment(f.ruleId)}${cwe}${ow}${loc}
// Scanner message: ${escapeBlockComment(f.message)}
// Optional integration: edit CONFIG at bottom; leave strings empty to skip network calls.
`;
}

function safeName(s: string): string {
  return s.replace(/[^a-zA-Z0-9_-]+/g, "_").slice(0, 80);
}

/** Safe inside block comments. */
function escapeBlockComment(s: string): string {
  return s.replace(/\*\//g, "* /").replace(/\r\n/g, "\n");
}

/** Safe inside single-quoted JS string literals in emitted tests. */
function escapeSingleQuoted(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

function routeMethodPath(f: Finding): { method: string; pathLiteral: string | null } {
  const r = f.route;
  if (!r) return { method: "GET", pathLiteral: null };
  return { method: r.method, pathLiteral: escapeSingleQuoted(r.fullPath) };
}

export function generateTests(findings: Finding[], outputDir: string): string[] {
  mkdirSync(outputDir, { recursive: true });
  const written: string[] = [];

  const weakSecretSamples = JSON.stringify(JWT_WEAK_SECRET_TEST.testSecrets.slice(0, 28));
  const forgedPayload = JSON.stringify(JWT_WEAK_SECRET_TEST.forgedPayload);

  findings.forEach((f, i) => {
    const base = `${safeName(f.ruleId)}_${i}`;
    let body = "";

    if (f.ruleId === "injection.prototype-pollution.tainted-flow" || f.findingKind === "PROTOTYPE_POLLUTION") {
      body = `${header(f)}
import { test } from 'node:test';
import assert from 'node:assert';

/** Set protoPostUrl to your JSON POST endpoint, or leave '' to skip fetch. */
const CONFIG = { protoPostUrl: '' };

test('RULE-PROTO-001: prototype pollution chain oracle', async () => {
  const before = Object.getOwnPropertyNames(Object.prototype);
  if (CONFIG.protoPostUrl) {
    const res = await fetch(CONFIG.protoPostUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ __proto__: { polluted: true } }),
    });
    assert.ok(res.status < 500, 'Unexpected 5xx from poisoned body');
  }
  const after = Object.getOwnPropertyNames(Object.prototype);
  assert.deepStrictEqual(after, before);
  assert.strictEqual(({}).polluted, undefined);
});
`;
    } else if (f.ruleId.includes("PROTO") && f.message.toLowerCase().includes("path")) {
      body = `${header(f)}
import { test } from 'node:test';
import assert from 'node:assert';

const CONFIG = { protoPostUrl: '' };

test('RULE-PROTO-002: path-shaped key must not pollute prototype', async () => {
  const before = Object.getOwnPropertyNames(Object.prototype);
  if (CONFIG.protoPostUrl) {
    const res = await fetch(CONFIG.protoPostUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ 'constructor.prototype.polluted': true }),
    });
    assert.ok(res.status < 500, 'Unexpected 5xx from path-shaped pollution payload');
  }
  const after = Object.getOwnPropertyNames(Object.prototype);
  assert.deepStrictEqual(after, before);
  assert.strictEqual(({}).polluted, undefined);
});
`;
    } else if (f.ruleId === "crypto.jwt.weak-secret-literal" || f.ruleId.toLowerCase().includes("jwt")) {
      body = `${header(f)}
import { createHmac } from 'node:crypto';
import { test } from 'node:test';
import assert from 'node:assert';

const WEAK_SECRETS = ${weakSecretSamples};
const FORGED_CLAIMS = ${forgedPayload};

function b64urlJson(obj) {
  return Buffer.from(JSON.stringify(obj), 'utf8')
    .toString('base64')
    .replace(/=+$/g, '')
    .replace(/\\+/g, '-')
    .replace(/\\//g, '_');
}

function forgeHs256(payload, secret) {
  const headerPart = b64urlJson({ alg: 'HS256', typ: 'JWT' });
  const payloadPart = b64urlJson(payload);
  const data = headerPart + '.' + payloadPart;
  const sig = createHmac('sha256', secret).update(data, 'utf8').digest('base64')
    .replace(/=+$/g, '')
    .replace(/\\+/g, '-')
    .replace(/\\//g, '_');
  return data + '.' + sig;
}

test('JWT: weak-secret forge primitive produces verifiable HS256 tokens', () => {
  let forgedAny = false;
  for (const secret of WEAK_SECRETS) {
    const token = forgeHs256(FORGED_CLAIMS, secret);
    assert.match(token, /^[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+$/);
    forgedAny = true;
  }
  assert.strictEqual(forgedAny, true);
});

const CONFIG = { jwtOracleBase: '', jwtOraclePath: '/api/me' };

test('JWT: forged admin token must not be accepted after secrets are hardened', async () => {
  if (!CONFIG.jwtOracleBase) return;
  const primarySecret = WEAK_SECRETS[0] ?? 'secret';
  const forged = forgeHs256(FORGED_CLAIMS, primarySecret);
  const url = new URL(CONFIG.jwtOraclePath, CONFIG.jwtOracleBase);
  const res = await fetch(url, { headers: { Authorization: 'Bearer ' + forged } });
  assert.ok(
    res.status === 401 || res.status === 403,
    'Expected 401/403 when verifying forged HS256 token after remediation; got ' + res.status
  );
});
`;
    } else if (
      f.ruleId === "AUTH-001" ||
      f.ruleId.startsWith("AUTH-") ||
      f.message.toLowerCase().includes("bola")
    ) {
      const { pathLiteral } = routeMethodPath(f);
      const pathJs = pathLiteral != null ? `'${pathLiteral}'` : "'/REPLACE_ME'";
      body = `${header(f)}
import { test } from 'node:test';
import assert from 'node:assert';

const CONFIG = {
  apiBase: '',
  tokenUserA: '',
  tokenUserB: '',
  resourcePath: ${pathJs},
};

test('BOLA / object-level auth: user B cannot access user A resource', async () => {
  if (!CONFIG.apiBase || !CONFIG.tokenUserA || !CONFIG.tokenUserB) return;
  const createUrl = new URL(CONFIG.resourcePath, CONFIG.apiBase);

  const created = await fetch(createUrl, {
    method: 'POST',
    headers: {
      Authorization: 'Bearer ' + CONFIG.tokenUserA,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ label: 'vibescan-bola-fixture' }),
  });
  assert.ok(
    created.status === 201 || created.status === 200 || created.status === 204,
    'Adjust POST body/route: expected resource creation as user A (got ' + created.status + ')'
  );
  let resourceUrl = createUrl;
  const loc = created.headers.get('location');
  if (loc) resourceUrl = new URL(loc, CONFIG.apiBase);

  const leaked = await fetch(resourceUrl, {
    method: 'GET',
    headers: { Authorization: 'Bearer ' + CONFIG.tokenUserB },
  });
  assert.ok(
    leaked.status === 401 || leaked.status === 403 || leaked.status === 404,
    'User B must not read/alter A\\'s resource (got ' + leaked.status + ')'
  );
});
`;
    } else {
      const { method, pathLiteral } = routeMethodPath(f);
      const title = escapeSingleQuoted(`${f.ruleId} — HTTP oracle / regression hook`);
      const pathJs = pathLiteral != null ? `'${pathLiteral}'` : 'CONFIG.targetPath';
      body = `${header(f)}
import { test } from 'node:test';
import assert from 'node:assert';

const CONFIG = {
  oracleBase: '',
  targetPath: '/REPLACE_ME',
};

test('${title}', async () => {
  if (!CONFIG.oracleBase) return;
  const path = ${pathJs};
  const url = new URL(typeof path === 'string' ? path : CONFIG.targetPath, CONFIG.oracleBase);
  const res = await fetch(url, { method: '${method}' });
  assert.ok(
    res.status < 500,
    'Oracle returned 5xx — fix server or CONFIG.oracleBase (status ' + res.status + ')'
  );
  // Add assertions for expected status/body for this rule (401/403, validation errors, etc.).
});
`;
    }

    const filePath = join(outputDir, `${base}.test.mjs`);
    writeFileSync(filePath, body, "utf-8");
    written.push(filePath);
    f.generatedTest = filePath;
  });

  return written;
}
