// Generated security tests from static findings (checklist Block 13).

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { JWT_WEAK_SECRET_TEST } from "../../attacks/crypto/jwt-weak-test.js";
import type { Finding } from "../types.js";

/** Optional context so defaults resolve from the scanned project tree. */
export interface GenerateTestsOptions {
  /** Workspace root: also checks `<root>/vibescan.tests.json`. */
  projectRoot?: string;
}

const CONFIG_HELPER_FILENAME = "vibescan-test-config.mjs";

function emitConfigHelper(projectRoot: string | undefined): string {
  const rootPush =
    projectRoot && projectRoot.length > 0
      ? `paths.push(join(${JSON.stringify(projectRoot)}, "vibescan.tests.json"));`
      : "";
  return `// Auto-generated by VibeScan — optional defaults for generated *.test.mjs files.
// Precedence: VIBESCAN_* env (non-empty) → merged JSON from search paths below → "".
// Add vibescan.tests.json next to this file or under project root / cwd. Keys: oracleBase, apiBase,
// jwtOracleBase, jwtOraclePath, protoPostUrl, tokenUserA, tokenUserB (all optional strings).
import { readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

function tryReadJson(path) {
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return null;
  }
}

export function vibescanTestDefaults() {
  const paths = [join(__dirname, "vibescan.tests.json")];
  ${rootPush}
  paths.push(join(process.cwd(), "vibescan.tests.json"));

  let fromFile = {};
  for (const p of paths) {
    const j = tryReadJson(p);
    if (j && typeof j === "object" && !Array.isArray(j)) {
      fromFile = { ...fromFile, ...j };
    }
  }

  const apiBase = process.env.VIBESCAN_API_BASE || fromFile.apiBase || "";
  const oracleBase = process.env.VIBESCAN_ORACLE_BASE || fromFile.oracleBase || "";
  const jwtOracleBase = process.env.VIBESCAN_JWT_ORACLE_BASE || fromFile.jwtOracleBase || "";
  const jwtOraclePath =
    process.env.VIBESCAN_JWT_ORACLE_PATH || fromFile.jwtOraclePath || "/api/me";
  const protoPostUrl = process.env.VIBESCAN_PROTO_POST_URL || fromFile.protoPostUrl || "";
  const tokenUserA = process.env.VIBESCAN_TOKEN_USER_A || fromFile.tokenUserA || "";
  const tokenUserB = process.env.VIBESCAN_TOKEN_USER_B || fromFile.tokenUserB || "";

  const sharedBase = oracleBase || apiBase || jwtOracleBase;

  return {
    oracleBase: oracleBase || sharedBase,
    apiBase: apiBase || sharedBase,
    jwtOracleBase: jwtOracleBase || oracleBase || apiBase || sharedBase,
    jwtOraclePath,
    protoPostUrl,
    tokenUserA,
    tokenUserB,
  };
}
`;
}

function attackClassLabel(f: Finding): string {
  if (f.ruleId.includes("jwt") || f.ruleId.toLowerCase().includes("jwt")) {
    return "Broken authentication / token forgery (JWT weak or predictable signing material)";
  }
  if (f.findingKind === "PROTOTYPE_POLLUTION" || f.ruleId.includes("prototype")) {
    return "Prototype pollution / unsafe object merge (A03)";
  }
  if (f.ruleId.includes("sql") || f.ruleId.includes("SQL")) {
    return "SQL injection / unsafe query construction (A03)";
  }
  if (f.ruleId.includes("command") || f.ruleId.includes("exec")) {
    return "Command injection / unsafe process invocation (A03)";
  }
  if (f.ruleId.includes("ssrf") || f.ruleId.includes("SSRF")) {
    return "Server-side request forgery / unsafe outbound URLs (A10)";
  }
  if (f.ruleId.startsWith("AUTH-") || f.message.toLowerCase().includes("bola")) {
    return "Broken access control / object-level authorization (BOLA-style)";
  }
  if (f.ruleId === "WEBHOOK-001") {
    return "Webhook signature verification gap";
  }
  if (f.ruleId === "SLOP-001") {
    return "Supply-chain / dependency confusion signal (verify package provenance)";
  }
  return "Regression oracle tied to the reported static finding — confirm with code review";
}

function routeScaffoldComment(f: Finding): string {
  const r = f.route;
  if (!r) {
    return `// Route: (unknown from graph) — set CONFIG.method, CONFIG.path, CONFIG.headers, CONFIG.query, CONFIG.bodyJson
// <REQUIRED> Replace placeholders; leave '' to skip integration calls.`;
  }
  const params = r.path.includes(":") ? r.path : r.fullPath;
  const hasParams = /:[^/]+/.test(params);
  return `// Route under test: ${r.method} ${r.fullPath}
// File declaring route: ${r.middlewares?.length ?? 0} middleware layer(s) (see scanner route graph)
${hasParams ? "// Path params: replace :id segments in CONFIG.path with concrete test IDs\n" : ""}// <REQUIRED> Set CONFIG.authorization and body/query to match your API contract`;
}

function header(f: Finding): string {
  const cwe = f.cwe != null ? ` · CWE-${f.cwe}` : "";
  const ow = f.owasp ? ` · OWASP ${f.owasp}` : "";
  const loc =
    f.filePath != null
      ? `\n// Source: ${escapeBlockComment(f.filePath)}:${f.line}`
      : `\n// Source line: ${f.line}`;
  const attack = escapeBlockComment(attackClassLabel(f));
  const routeNote = routeScaffoldComment(f);
  return `// Generated by VibeScan — security test scaffold (not hands-off pentest)
// Rule: ${escapeBlockComment(f.ruleId)}${cwe}${ow}${loc}
// Attack class: ${attack}
// Scanner message: ${escapeBlockComment(f.message)}
${routeNote}
// CONFIG: optional shared defaults via ./vibescan-test-config.mjs (VIBESCAN_* env + vibescan.tests.json).
// Per-file fields below still override; empty strings skip live HTTP calls.
`;
}

function safeName(s: string): string {
  return s.replace(/[^a-zA-Z0-9_-]+/g, "_").slice(0, 80);
}

/** Safe inside block comments. */
function escapeBlockComment(s: string): string {
  return s.replace(/\*\//g, "* /").replace(/\r\n/g, "\n");
}

/** Safe inside single-quoted JS string literals in emitted tests. */
function escapeSingleQuoted(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

function routeMethodPath(f: Finding): { method: string; pathLiteral: string | null } {
  const r = f.route;
  if (!r) return { method: "GET", pathLiteral: null };
  return { method: r.method, pathLiteral: escapeSingleQuoted(r.fullPath) };
}

export function generateTests(
  findings: Finding[],
  outputDir: string,
  options?: GenerateTestsOptions
): string[] {
  mkdirSync(outputDir, { recursive: true });
  writeFileSync(join(outputDir, CONFIG_HELPER_FILENAME), emitConfigHelper(options?.projectRoot), "utf-8");
  const written: string[] = [];

  const weakSecretSamples = JSON.stringify(JWT_WEAK_SECRET_TEST.testSecrets.slice(0, 28));
  const forgedPayload = JSON.stringify(JWT_WEAK_SECRET_TEST.forgedPayload);

  findings.forEach((f, i) => {
    const base = `${safeName(f.ruleId)}_${i}`;
    let body = "";

    if (f.ruleId === "injection.prototype-pollution.tainted-flow" || f.findingKind === "PROTOTYPE_POLLUTION") {
      body = `${header(f)}
import { vibescanTestDefaults } from './${CONFIG_HELPER_FILENAME}';
import { test } from 'node:test';
import assert from 'node:assert';

/** JSON POST endpoint that merges/parses body (prototype pollution probe); set BASE.protoPostUrl or CONFIG.protoPostUrl. */
const BASE = vibescanTestDefaults();
const CONFIG = {
  protoPostUrl: BASE.protoPostUrl,
  headers: { 'Content-Type': 'application/json', 'X-Test-Client': 'vibescan-scaffold' },
  bodyJson: { __proto__: { polluted: true } },
};

test('RULE-PROTO-001: prototype pollution chain oracle', async () => {
  const before = Object.getOwnPropertyNames(Object.prototype);
  if (CONFIG.protoPostUrl) {
    const res = await fetch(CONFIG.protoPostUrl, {
      method: 'POST',
      headers: CONFIG.headers,
      body: JSON.stringify(CONFIG.bodyJson),
    });
    assert.ok(res.status < 500, 'Unexpected 5xx from poisoned body');
  }
  const after = Object.getOwnPropertyNames(Object.prototype);
  assert.deepStrictEqual(after, before);
  assert.strictEqual(({}).polluted, undefined);
});
`;
    } else if (f.ruleId.includes("PROTO") && f.message.toLowerCase().includes("path")) {
      body = `${header(f)}
import { vibescanTestDefaults } from './${CONFIG_HELPER_FILENAME}';
import { test } from 'node:test';
import assert from 'node:assert';

const BASE = vibescanTestDefaults();
const CONFIG = {
  protoPostUrl: BASE.protoPostUrl,
  headers: { 'Content-Type': 'application/json', 'X-Test-Client': 'vibescan-scaffold' },
};

test('RULE-PROTO-002: path-shaped key must not pollute prototype', async () => {
  const before = Object.getOwnPropertyNames(Object.prototype);
  if (CONFIG.protoPostUrl) {
    const res = await fetch(CONFIG.protoPostUrl, {
      method: 'POST',
      headers: CONFIG.headers,
      body: JSON.stringify({ 'constructor.prototype.polluted': true }),
    });
    assert.ok(res.status < 500, 'Unexpected 5xx from path-shaped pollution payload');
  }
  const after = Object.getOwnPropertyNames(Object.prototype);
  assert.deepStrictEqual(after, before);
  assert.strictEqual(({}).polluted, undefined);
});
`;
    } else if (f.ruleId === "crypto.jwt.weak-secret-literal" || f.ruleId.toLowerCase().includes("jwt")) {
      body = `${header(f)}
import { createHmac } from 'node:crypto';
import { vibescanTestDefaults } from './${CONFIG_HELPER_FILENAME}';
import { test } from 'node:test';
import assert from 'node:assert';

const WEAK_SECRETS = ${weakSecretSamples};
const FORGED_CLAIMS = ${forgedPayload};

function b64urlJson(obj) {
  return Buffer.from(JSON.stringify(obj), 'utf8')
    .toString('base64')
    .replace(/=+$/g, '')
    .replace(/\\+/g, '-')
    .replace(/\\//g, '_');
}

function forgeHs256(payload, secret) {
  const headerPart = b64urlJson({ alg: 'HS256', typ: 'JWT' });
  const payloadPart = b64urlJson(payload);
  const data = headerPart + '.' + payloadPart;
  const sig = createHmac('sha256', secret).update(data, 'utf8').digest('base64')
    .replace(/=+$/g, '')
    .replace(/\\+/g, '-')
    .replace(/\\//g, '_');
  return data + '.' + sig;
}

test('JWT: weak-secret forge primitive produces verifiable HS256 tokens', () => {
  let forgedAny = false;
  for (const secret of WEAK_SECRETS) {
    const token = forgeHs256(FORGED_CLAIMS, secret);
    assert.match(token, /^[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+$/);
    forgedAny = true;
  }
  assert.strictEqual(forgedAny, true);
});

const CONFIG = { jwtOracleBase: '', jwtOraclePath: '/api/me' };

test('JWT: forged admin token must not be accepted after secrets are hardened', async () => {
  if (!CONFIG.jwtOracleBase) return;
  const primarySecret = WEAK_SECRETS[0] ?? 'secret';
  const forged = forgeHs256(FORGED_CLAIMS, primarySecret);
  const url = new URL(CONFIG.jwtOraclePath, CONFIG.jwtOracleBase);
  const res = await fetch(url, { headers: { Authorization: 'Bearer ' + forged } });
  assert.ok(
    res.status === 401 || res.status === 403,
    'Expected 401/403 when verifying forged HS256 token after remediation; got ' + res.status
  );
});
`;
    } else if (
      f.ruleId === "AUTH-001" ||
      f.ruleId.startsWith("AUTH-") ||
      f.message.toLowerCase().includes("bola")
    ) {
      const { pathLiteral } = routeMethodPath(f);
      const pathJs = pathLiteral != null ? `'${pathLiteral}'` : "'/REPLACE_ME'";
      body = `${header(f)}
import { vibescanTestDefaults } from './${CONFIG_HELPER_FILENAME}';
import { test } from 'node:test';
import assert from 'node:assert';

const BASE = vibescanTestDefaults();
const CONFIG = {
  apiBase: BASE.apiBase,
  tokenUserA: BASE.tokenUserA,
  tokenUserB: BASE.tokenUserB,
  resourcePath: ${pathJs},
  /** Extra headers for WAF / trace IDs */
  headersCommon: {} as Record<string, string>,
};

test('BOLA / object-level auth: user B cannot access user A resource', async () => {
  if (!CONFIG.apiBase || !CONFIG.tokenUserA || !CONFIG.tokenUserB) return;
  const createUrl = new URL(CONFIG.resourcePath, CONFIG.apiBase);

  const created = await fetch(createUrl, {
    method: 'POST',
    headers: {
      Authorization: 'Bearer ' + CONFIG.tokenUserA,
      'Content-Type': 'application/json',
      ...CONFIG.headersCommon,
    },
    body: JSON.stringify({ label: 'vibescan-bola-fixture' }),
  });
  assert.ok(
    created.status === 201 || created.status === 200 || created.status === 204,
    'Adjust POST body/route: expected resource creation as user A (got ' + created.status + ')'
  );
  let resourceUrl = createUrl;
  const loc = created.headers.get('location');
  if (loc) resourceUrl = new URL(loc, CONFIG.apiBase);

  const leaked = await fetch(resourceUrl, {
    method: 'GET',
    headers: { Authorization: 'Bearer ' + CONFIG.tokenUserB, ...CONFIG.headersCommon },
  });
  assert.ok(
    leaked.status === 401 || leaked.status === 403 || leaked.status === 404,
    'User B must not read/alter A\\'s resource (got ' + leaked.status + ')'
  );
});
`;
    } else {
      const { method, pathLiteral } = routeMethodPath(f);
      const title = escapeSingleQuoted(`${f.ruleId} — HTTP oracle / regression hook`);
      const pathJs = pathLiteral != null ? `'${pathLiteral}'` : 'CONFIG.targetPath';
      body = `${header(f)}
import { vibescanTestDefaults } from './${CONFIG_HELPER_FILENAME}';
import { test } from 'node:test';
import assert from 'node:assert';

const BASE = vibescanTestDefaults();
const CONFIG = {
  oracleBase: BASE.oracleBase,
  targetPath: '/REPLACE_ME', // path when route graph missing
  /** Query string without leading '?', e.g. id=1&debug=true */
  queryString: '',
  headers: {
    // 'Authorization': 'Bearer <token>', // <REQUIRED> if endpoint is protected
    // 'Content-Type': 'application/json',
  },
  /** For ${method !== 'GET' && method !== 'HEAD' ? "writes" : "reads"} — adjust to API contract */
  bodyJson: {} as Record<string, unknown>,
};

test('${title}', async () => {
  if (!CONFIG.oracleBase) return;
  const path = ${pathJs};
  const qs = CONFIG.queryString ? '?' + CONFIG.queryString : '';
  const url = new URL((typeof path === 'string' ? path : CONFIG.targetPath) + qs, CONFIG.oracleBase);
  const init = {
    method: '${method}',
    headers: CONFIG.headers,
    ${method !== 'GET' && method !== 'HEAD' ? "body: Object.keys(CONFIG.bodyJson).length ? JSON.stringify(CONFIG.bodyJson) : undefined," : ""}
  };
  const res = await fetch(url, init);
  assert.ok(
    res.status < 500,
    'Oracle returned 5xx — fix server or CONFIG.oracleBase (status ' + res.status + ')'
  );
  // <REQUIRED> Assert expected status/body for this rule (401/403, validation errors, etc.).
});
`;
    }

    const filePath = join(outputDir, `${base}.test.mjs`);
    writeFileSync(filePath, body, "utf-8");
    written.push(filePath);
    f.generatedTest = filePath;
  });

  return written;
}
