import fs from "node:fs/promises";
import path from "node:path";

const BANNER = `// Generated by VibeScan — do not delete, run in CI
// TODO: point this import at your Express app export (see vibescan README).
`;

/**
 * @param {import('../types.js').Finding[]} findings
 * @param {string} outputDir
 */
export async function generateTests(findings, outputDir) {
  await fs.mkdir(outputDir, { recursive: true });
  const byRule = new Map();
  for (const f of findings) {
    if (!byRule.has(f.ruleId)) byRule.set(f.ruleId, []);
    byRule.get(f.ruleId).push(f);
  }

  let idx = 0;
  for (const [ruleId, group] of byRule) {
    const file = path.join(outputDir, `vibescan-${ruleId.replace(/[^a-z0-9-]/gi, "-")}-${idx++}.test.js`);
    const body = buildFile(ruleId, group);
    await fs.writeFile(file, body, "utf8");
  }

  if (!findings.length) {
    const stub = path.join(outputDir, "vibescan-placeholder.test.js");
    await fs.writeFile(
      stub,
      `${BANNER}
import { describe, test, expect } from '@jest/globals';

describe('VibeScan generated tests', () => {
  test('placeholder — no findings to generate from', () => {
    expect(true).toBe(true);
  });
});
`,
      "utf8"
    );
  }
}

/**
 * @param {string} ruleId
 * @param {import('../types.js').Finding[]} group
 */
function buildFile(ruleId, group) {
  const tests = group
    .map((f, i) => {
      if (ruleId.startsWith("RULE-PROTO")) {
        return `
  test('${ruleId}: prototype pollution oracle ${i + 1}', async () => {
    const before = Object.getOwnPropertyNames(Object.prototype);
    // await request(app).post('${f.snippet || "/"}').send({"__proto__": {"polluted": true}});
    expect(Object.getOwnPropertyNames(Object.prototype)).toEqual(before);
    expect({}.polluted).toBeUndefined();
  });`;
      }
      if (ruleId === "RULE-AUTH-001") {
        return `
  test('${ruleId}: BOLA two-user pattern ${i + 1}', async () => {
    // const tokenA = await getToken('userA@test.com');
    // const tokenB = await getToken('userB@test.com');
    // const resCreate = await request(app).post('/api/resource').set('Authorization', \`Bearer \${tokenA}\`).send({ name: 'test' });
    // const resourceId = resCreate.body.id;
    // const resFetch = await request(app).get(\`/api/resource/\${resourceId}\`).set('Authorization', \`Bearer \${tokenB}\`);
    // expect(resFetch.status).toBe(403);
    expect(true).toBe(true);
  });`;
      }
      return `
  test('${ruleId}: finding ${i + 1} at ${f.file}:${f.line}', async () => {
    const payloads = ["payload1", "payload2"];
    for (const payload of payloads) {
      // const res = await request(app).post('/api/endpoint').send({ field: payload });
      // expect(res.status).not.toBe(500);
      expect(payload).toBeDefined();
    }
  });`;
    })
    .join("\n");

  return `${BANNER}
import { describe, test, expect } from '@jest/globals';
// import request from 'supertest';
// import app from '../path/to/app.js';

describe('VibeScan — ${ruleId}', () => {
${tests}
});
`;
}
